

```{r}
library(mirt)
n_i=100
th=sort(rnorm(1000))
resp_th= function(list){
  df=data.frame(th)
  for (i in 1:length(list)){
    df[[i+1]]<-list[[i]][, ncol(list[[i]])]
  }
  colnames(df)<-c("th", paste("Item", 1:(length(list)),sep='') )
  df
}

a_i<-sort(c(runif(n_i-6, min=0.1, max=3), 0, 0.14, 0.5, 1, 1.5, 3) )
bs<-data.frame(b1=0, b2=sort(c(runif(n_i-5, min=0.1, max=3), 0, 0.1, 1.4, 2, 3 )) )
b_2<-bs[,2]
bs.c<-data.frame(b1=0, b2=sort(c(runif(n_i-3, min=-3, max=3), -3, 0,3 )) ) 
a=1
all.a2.val<-data.frame(a1=0, a2=sort( c(runif(n_i-3, min=-3, max=3), -2, 1, 3 )), a3=2 )
all.c2.val<-data.frame(c1=0, c2=sort(c( runif(n_i-3, min=-3, max=3), -2, 1, 3 )), c3=2 )
```


```{r}
ordered.grm<-readRDS("C:/Users/Roza/Desktop/Order.12.15.23/Data/ordered.grm.Vary_b,a=1.RData")
ordered.grm.a<-readRDS("C:/Users/Roza/Desktop/Order.12.15.23/Data/ordered.grm.Vary_a.RData")

ordered.gpcm<-readRDS("C:/Users/Roza/Desktop/Order.12.15.23/Data/ordered.gpcm.Vary_b,a=1.RData")
ordered.gpcm.a<-readRDS("C:/Users/Roza/Desktop/Order.12.15.23/Data/ordered.gpcm.Vary_a.RData")
crossed.pcm<-readRDS("C:/Users/Roza/Desktop/Order.12.15.23/Data/crossed.pcm.RData")

all.a2<-readRDS("C:/Users/Roza/Desktop/Order.12.15.23/Data/all.a2.RData")
all.c2<-readRDS("C:/Users/Roza/Desktop/Order.12.15.23/Data/all.c2.RData")

ordered.grm.const<-readRDS("C:/Users/Roza/Desktop/Order.12.15.23/Data/ordered.grm.const.RData")
ordered.grm.a.const<-readRDS("C:/Users/Roza/Desktop/Order.12.15.23/Data/ordered.grm.a.const.RData")

ordered.grm4b<-readRDS("C:/Users/Roza/Desktop/Order.12.15.23/Data/ordered.grm4b.RData")
ordered.grm4a<-readRDS("C:/Users/Roza/Desktop/Order.12.15.23/Data/ordered.grm4a.RData")
```


```{r}
simnrm<-function(th, c, a) {
  K<-length(a)
  z<-list()
  for (k in 1:K) {
    kern<-a[k]*th+c[k]
    z[[k]]<-exp(kern)
  }
  z<-do.call("cbind", z)
  den<-rowSums(z)
  p<-z/den
  colnames(p)<-paste("P.",1:ncol(p), sep='')
  resp<-numeric()
  for (i in 1:length(th)) resp[i]<-which(rmultinom(1, 1, p[i,])[,1]>0)-1
  id=1:length(th)
  data.frame(cbind(id, th.true=th, p, resp))
}


# For NRM
fun.nrm<-function(list, c, as){
  df<-data.frame()
  for (i in 1:length(list)){
    pcm1=list[[i]][,3:5]
    th.true=list[[i]][,2]
    O<-numeric()
    for (thj in th.true) {
      p<-pnorm(thj)
      p<-runif(1,0,p)
      thi<-qnorm(p)
      p.first<-simnrm(thi, c=c[i,], a=as.numeric(as[i,]) )[,3:5]
      index=match(thj, th.true)
      p.second<-pcm1[index,]
      p=rbind(p.first, p.second)
      p0<-p[2,1]*(p[1,2]+p[1,3])#x_i>x_j if x_j=0
      p1<-p[2,2]*(p[1,3])#x_i>x_j if x_j=1
      O[as.character(thj)]<-p0+p1
      }
    order=1-mean(O)
    df<-rbind( df, order)
  }
  cbind(as, c, order=df)
}
```


```{r}
ind4=function(list){
  resp=resp_th(list)[,-c(1, 2)]
  l2=list()
  m <- mirt(resp, 1, itemtype = "nominal")
  par<-data.frame(coef(m, IRTpars=TRUE, simplify=TRUE))
  par=par[,c("items.a1", "items.a2", "items.a3", "items.c1", "items.c2", "items.c3" )]
  th.est<-fscores(m)
  colnames(th.est)="th.est"
  for (i in 1:ncol(resp)){
    item<-extract.item(m, i)
    pr<-probtrace(item, th.est)
    id=1:nrow(resp)
    df=list(cbind(id, th.est, pr, resp[i]))
    l2[i]=df
  }
  c=par[,4:6]
  as=par[,1:3]
  list=l2
  s4=fun.nrm(list, c, as)
  s4[,7]
}
```




```{r}
d1=ind4(ordered.grm.a)
d2=ind4(ordered.grm)
d3=ind4(ordered.gpcm.a)
d4=ind4(ordered.gpcm) 
d5=ind4(crossed.pcm) 
d6=ind4(all.a2)
d7=ind4(all.c2)
```



```{r}
fun.nrm1<-function(list, c, as){
  df<-data.frame()
  for (i in 1:length(list)){
    pcm1=list[[i]][,3:6]
    th.true=list[[i]][,2]
    O<-numeric()
    for (thj in th.true) {
      p<-pnorm(thj)
      p<-runif(1,0,p)
      thi<-qnorm(p)
      p.first<-simnrm(thi, c=c[i,], a=as.numeric(as[i,]) )[,3:6]
      index=match(thj, th.true)
      p.second<-pcm1[index,]
      p=rbind(p.first, p.second)
      p0<-p[2,1]*(p[1,2]+p[1,3] +p[1,4])#x_i>x_j if x_j=0
      p1<-p[2,2]*(p[1,3]+p[1,4])#x_i>x_j if x_j=1
      p2<-p[2,3]*(p[1,4])
      O[as.character(thj)]<-p0+p1+p2
      }
    order=1-mean(O)
    df<-rbind( df, order)
  }
  cbind(as, c, order=df)
}
```


```{r}
ind41=function(list){
  resp=resp_th(list)[,-c(1, 2)]
  l2=list()
  m <- mirt(resp, 1, itemtype = "nominal")
  par<-data.frame(coef(m, IRTpars=TRUE, simplify=TRUE))
  par=par[,c("items.a1", "items.a2", "items.a3", "items.a4", "items.c1", "items.c2", "items.c3", "items.c4" )]
  th.est<-fscores(m)
  colnames(th.est)="th.est"
  for (i in 1:ncol(resp)){
    item<-extract.item(m, i)
    pr<-probtrace(item, th.est)
    id=1:nrow(resp)
    df=list(cbind(id, th.est, pr, resp[i]))
    l2[i]=df
  }
  c=par[,5:8]
  as=par[,1:4]
  list=l2
  s4=fun.nrm(list, c, as)
  s4[,9]
}
```



```{r}
d8=ind41(ordered.grm.const)
d9=ind41(ordered.grm.a.const)
d10=ind41(ordered.grm4b[-100])
d11=ind41(ordered.grm4a)
```


```{r}
measure2=list(d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11)
saveRDS(measure2, file="C:/Users/Roza/Desktop/Order.12.15.23/Data/measure2.RData")
```






















