

```{r}
n_i=100
th=sort(rnorm(1000))
resp_th= function(list){
  df=data.frame(th)
  for (i in 1:length(list)){
    df[[i+1]]<-list[[i]][, ncol(list[[i]])]
  }
  colnames(df)<-c("th", paste("Item", 1:(length(list)),sep='') )
  df
}

a_i<-sort(c(runif(n_i-6, min=0.1, max=3), 0, 0.14, 0.5, 1, 1.5, 3) )
bs<-data.frame(b1=0, b2=sort(c(runif(n_i-5, min=0.1, max=3), 0, 0.1, 1.4, 2, 3 )) )
b_2<-bs[,2]
bs.c<-data.frame(b1=0, b2=sort(c(runif(n_i-3, min=-3, max=3), -3, 0,3 )) ) 
a=1
all.a2.val<-data.frame(a1=0, a2=sort( c(runif(n_i-3, min=-3, max=3), -2, 1, 3 )), a3=2 )
all.c2.val<-data.frame(c1=0, c2=sort(c( runif(n_i-3, min=-3, max=3), -2, 1, 3 )), c3=2 )
```


```{r}
ordered.grm<-readRDS("C:/Users/Roza/Desktop/Order.12.15.23/Data/ordered.grm.Vary_b,a=1.RData")
ordered.grm.a<-readRDS("C:/Users/Roza/Desktop/Order.12.15.23/Data/ordered.grm.Vary_a.RData")

ordered.gpcm<-readRDS("C:/Users/Roza/Desktop/Order.12.15.23/Data/ordered.gpcm.Vary_b,a=1.RData")
ordered.gpcm.a<-readRDS("C:/Users/Roza/Desktop/Order.12.15.23/Data/ordered.gpcm.Vary_a.RData")
crossed.pcm<-readRDS("C:/Users/Roza/Desktop/Order.12.15.23/Data/crossed.pcm.RData")

all.a2<-readRDS("C:/Users/Roza/Desktop/Order.12.15.23/Data/all.a2.RData")
all.c2<-readRDS("C:/Users/Roza/Desktop/Order.12.15.23/Data/all.c2.RData")

ordered.grm.const<-readRDS("C:/Users/Roza/Desktop/Order.12.15.23/Data/ordered.grm.const.RData")
ordered.grm.a.const<-readRDS("C:/Users/Roza/Desktop/Order.12.15.23/Data/ordered.grm.a.const.RData")

ordered.grm4b<-readRDS("C:/Users/Roza/Desktop/Order.12.15.23/Data/ordered.grm4b.RData")
ordered.grm4a<-readRDS("C:/Users/Roza/Desktop/Order.12.15.23/Data/ordered.grm4a.RData")
```





```{r}
resp.grm<-resp_th(ordered.grm.a)
est.nrm<-mirt(resp.grm[,-1], 1, itemtype="nominal")
itempar <- data.frame(coef(est.nrm, IRTpars=TRUE, simplify=TRUE) )
itempar.est<-itempar[,c("items.a1", "items.a2", "items.a3" )]
d=data.frame(d1=itempar.est[,2]-itempar.est[,1], d2=itempar.est[,3]-itempar.est[,2])
d01=data.frame()
for ( i in 2:n_i){
  if (d[i,1]>0 & d[i,2]>0) {
    f=mean(as.numeric(d[i,]))/3
  }
  else{ f=mean(as.numeric(d[i,which(d[i,]<0)]))/3 }
  d01=rbind(d01, f)
}
```


```{r}
resp.grm<-resp_th(ordered.grm)
est.nrm<-mirt(resp.grm[,-1], 1, itemtype="nominal")
itempar <- data.frame(coef(est.nrm, IRTpars=TRUE, simplify=TRUE) )
itempar.est<-itempar[,c("items.a1", "items.a2", "items.a3" )]

d=data.frame(d1=itempar.est[,2]-itempar.est[,1], d2=itempar.est[,3]-itempar.est[,2])
d02=data.frame()
for ( i in 2:n_i){
  if (d[i,1]>0 & d[i,2]>0) {
    f=mean(as.numeric(d[i,]))/3
  }
  else{ f=mean(as.numeric(d[i,which(d[i,]<0)]))/3}
  d02=rbind(d02, f)
}

```


```{r}
resp.grm<-resp_th(ordered.gpcm.a)
est.nrm<-mirt(resp.grm[,-1], 1, itemtype="nominal")
itempar <- data.frame(coef(est.nrm, IRTpars=TRUE, simplify=TRUE) )
itempar.est<-itempar[,c("items.a1", "items.a2", "items.a3" )]

d=data.frame(d1=itempar.est[,2]-itempar.est[,1], d2=itempar.est[,3]-itempar.est[,2])
d03=data.frame()
for ( i in 1:n_i){
  if (d[i,1]>0 & d[i,2]>0) {
    f=mean(as.numeric(d[i,]))/3
  }
  else{ f=mean(as.numeric(d[i,which(d[i,]<0)]))/3}
  d03=rbind(d03, f)
}
```


```{r}
resp.grm<-resp_th(ordered.gpcm)
est.nrm<-mirt(resp.grm[,-1], 1, itemtype="nominal")
itempar <- data.frame(coef(est.nrm, IRTpars=TRUE, simplify=TRUE) )
itempar.est<-itempar[,c("items.a1", "items.a2", "items.a3" )]

d=data.frame(d1=itempar.est[,2]-itempar.est[,1], d2=itempar.est[,3]-itempar.est[,2])
d04=data.frame()
for ( i in 1:n_i){
  if (d[i,1]>0 & d[i,2]>0) {
    f=mean(as.numeric(d[i,]))/3
  }
  else{ f=mean(as.numeric(d[i,which(d[i,]<0)]))/3}
  d04=rbind(d04, f)
}
```


```{r}
resp<-resp_th(crossed.pcm)
est.nrm<-mirt(resp[,-1], 1, itemtype="nominal")
itempar <- data.frame(coef(est.nrm, IRTpars=TRUE, simplify=TRUE) )
itempar.est<-itempar[,c("items.a1", "items.a2", "items.a3" )]

d=data.frame(d1=itempar.est[,2]-itempar.est[,1], d2=itempar.est[,3]-itempar.est[,2])
d05=data.frame()
for ( i in 1:n_i){
  if (d[i,1]>0 & d[i,2]>0) {
    f=mean(as.numeric(d[i,]))/3
  }
  else{ f=mean(as.numeric(d[i,which(d[i,]<0)]))/3}
  d05=rbind(d05, f)
}
```


```{r}
resp<-resp_th(all.a2)
est.nrm<-mirt(resp[,-1], 1, itemtype="nominal")
itempar <- data.frame(coef(est.nrm, IRTpars=TRUE, simplify=TRUE) )
itempar.est<-itempar[,c("items.a1", "items.a2", "items.a3" )]

d=data.frame(d1=itempar.est[,2]-itempar.est[,1], d2=itempar.est[,3]-itempar.est[,2])
d06=data.frame()
for ( i in 1:n_i){
  if (d[i,1]>0 & d[i,2]>0) {
    f=mean(as.numeric(d[i,]))/3
  }
  else{ f=mean(as.numeric(d[i,which(d[i,]<0)]))/3}
  d06=rbind(d06, f)
}
```


```{r}
resp<-resp_th(all.c2)
est.nrm<-mirt(resp[,-1], 1, itemtype="nominal")
itempar <- data.frame(coef(est.nrm, IRTpars=TRUE, simplify=TRUE) )
itempar.est<-itempar[,c("items.a1", "items.a2", "items.a3" )]

d=data.frame(d1=itempar.est[,2]-itempar.est[,1], d2=itempar.est[,3]-itempar.est[,2])
d07=data.frame()
for ( i in 1:n_i){
  if (d[i,1]>0 & d[i,2]>0) {
    f=mean(as.numeric(d[i,]))/3
  }
  else{ f=mean(as.numeric(d[i,which(d[i,]<0)]))/3}
  d07=rbind(d07, f)
}
```


```{r}
resp<-resp_th(ordered.grm.const)
est.nrm<-mirt(resp[,-1], 1, itemtype="nominal")
itempar <- data.frame(coef(est.nrm, IRTpars=TRUE, simplify=TRUE) )
itempar.est<-itempar[,c("items.a1", "items.a2", "items.a3", "items.a4")]

d=data.frame(d1=itempar.est[,2]-itempar.est[,1], d2=itempar.est[,3]-itempar.est[,2], d3=itempar.est[,4]-itempar.est[,3])
d08=data.frame()
for ( i in 1:n_i){
  if (d[i,1]>0 & d[i,2]>0 & d[i,3]>0) {
    f=mean(as.numeric(d[i,]))/3
  }
  else{ f=mean(as.numeric(d[i,which(d[i,]<0)]))/3}
  d08=rbind(d08, f)
}
```


```{r}
resp<-resp_th(ordered.grm.a.const)
est.nrm<-mirt(resp[,-1], 1, itemtype="nominal")
itempar <- data.frame(coef(est.nrm, IRTpars=TRUE, simplify=TRUE) )
itempar.est<-itempar[,c("items.a1", "items.a2", "items.a3", "items.a4")]
d=data.frame(d1=itempar.est[,2]-itempar.est[,1], d2=itempar.est[,3]-itempar.est[,2], d3=itempar.est[,4]-itempar.est[,3])
d09=data.frame()
for ( i in 2:n_i){
  if (d[i,1]>0 & d[i,2]>0 & d[i,3]>0) {
    f=mean(as.numeric(d[i,]))/3
  }
  else{ f=mean(as.numeric(d[i,which(d[i,]<0)]))/3}
  d09=rbind(d09, f)
}

```


```{r}
resp<-resp_th(ordered.grm4b)
est.nrm<-mirt(resp[,-1], 1, itemtype="nominal")
itempar <- data.frame(coef(est.nrm, IRTpars=TRUE, simplify=TRUE) )
itempar.est<-itempar[,c("items.a1", "items.a2", "items.a3", "items.a4")]

d=data.frame(d1=itempar.est[,2]-itempar.est[,1], d2=itempar.est[,3]-itempar.est[,2], d3=itempar.est[,4]-itempar.est[,3])
d010=data.frame()
for ( i in 2:(n_i-1)){
  if (d[i,1]>0 & d[i,2]>0 & d[i,3]>0) {
    f=mean(as.numeric(d[i,]))/3
  }
  else{ f=mean(as.numeric(d[i,which(d[i,]<0)]))/3}
  d010=rbind(d010, f)
}
```


```{r}
resp<-resp_th(ordered.grm4a)
est.nrm<-mirt(resp[,-1], 1, itemtype="nominal")
itempar <- data.frame(coef(est.nrm, IRTpars=TRUE, simplify=TRUE) )
itempar.est<-itempar[,c("items.a1", "items.a2", "items.a3", "items.a4")]

d=data.frame(d1=itempar.est[,2]-itempar.est[,1], d2=itempar.est[,3]-itempar.est[,2], d3=itempar.est[,4]-itempar.est[,3])
d011=data.frame()
for ( i in 1:n_i){
  if (d[i,1]>0 & d[i,2]>0 & d[i,3]>0) {
    f=mean(as.numeric(d[i,]))/3
  }
  else{ f=mean(as.numeric(d[i,which(d[i,]<0)]))/3}
  d011=rbind(d011, f)
}

```


```{r}
measure8=list(d01, d02, d03, d04, d05, d06, d07, d08, d09, d010, d011 )
saveRDS(measure8, file="C:/Users/Roza/Desktop/Order.12.15.23/Data/measure8.RData")

```






